version: "3.8"

volumes:
  redis-data:
    driver: local
  backup: # Added the missing volume declaration
    driver: local

networks:
  task-manager-pubic-network:
    labels:
      - com.packtpub.compose.app=task-manager
  redis-network: # Added the missing network declaration
    labels:
      - com.packtpub.compose.app=task-manager

services:
  task-manager:
    build: .
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis:6379
    depends_on:
      redis:
        condition: service_healthy
      redis-populate:
        condition: service_completed_successfully
    networks:
      - task-manager-pubic-network
      - redis-network
    labels:
      - com.packtpub.compose.app=task-manager

  redis:
    image: redis
    ports:
      - 6379:6379
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
      - backup:/backup
    networks:
      - redis-network
    labels:
      - com.packtpub.compose.app=task-manager

  redis-populate:
    image: redis
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - HOST=redis
      - PORT=6379
    volumes:
      - ./redis-populate.txt:/redis-populate.txt
      - ./redis-populate.sh:/redis-populate.sh
    command: ["/redis-populate.sh", "/redis-populate.txt"]
    networks:
      - task-manager-pubic-network
      - redis-network
    labels:
      - com.packtpub.compose.app=task-manager
