version: "3"

services:
  mysql:
    image: mysql
    restart: always
  frontend:
    build: ./frontend
    ports:
      - "3333:3000"
    depends_on:
      - mysql
  backend:
    build: ./api
    ports:
      - "5555:5000"
    depends_on:
      - mysql
  adminer:
    image: adminer
    ports:
      - "8888:8080"
    depends_on:
      - mysql
